# Generated by Django 4.0.6 on 2022-07-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_user',
            old_name='log_in',
            new_name='log_id',
        ),
    ]
